services:
  - type: web
    name: gmaps-ia-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootDirectory: .
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ZAPI_INSTANCE
        sync: false
      - key: ZAPI_TOKEN
        sync: false
